name: ✨ Feature Request
description: Sugiere una idea o nueva funcionalidad para el proyecto.
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Asegurate de que tu propuesta resuelva un problema real y esté alineada con el objetivo del proyecto.
  - type: textarea
    id: problem
    attributes:
      label: ¿Cuál es el problema?
      description: Describe el problema que estás intentando resolver (el "por qué").
      placeholder: Siempre me frustra cuando intento hacer X y ocurre Y...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solución propuesta
      description: Describe la solución que te gustaría ver implementada (el "qué").
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Criterios de aceptación
      description: ¿Cómo sabremos que esta funcionalidad está terminada y exitosa?
      placeholder: |
        - [ ] El usuario puede...
        - [ ] El sistema valida que...
    validations:
      required: true
